Repository ocean-ds/ocean-web, pull requests merged in 2020-08, with the labels that each got.

#159 feat: Button component
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/Button/Button.tsx
  src/Button/__tests__/Button.test.tsx
  src/Button/index.ts
  src/Button/stories/Button.stories.mdx
  src/Button/styles/button.scss
  src/Grid/stories/Col.stories.mdx
  src/Grid/stories/Container.stories.mdx
  src/Grid/stories/Grid.stories.mdx
  src/Grid/stories/Row.stories.mdx
  src/Grid/styles/row.scss
  src/Grid/styles/stories.scss
  src/Typography/__tests__/Typography.test.tsx
  src/Typography/stories/Typography.stories.mdx
  src/_stories/Examples.stories.mdx
  src/_util/type.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#169 feat: Adds input component
  src/Input/Input.tsx
  src/Input/__tests__/Input.test.tsx
  src/Input/index.ts
  src/Input/stories/Input.stories.mdx
  src/Input/styles/input.scss
  src/index.ts
Labels: documentation, enhancement

#191 fix: button styles
  src/Button/stories/Button.stories.mdx
  src/Button/styles/button.scss
Labels: bug

#202 feat: adds checkbox
  package.json
  src/Checkbox/Checkbox.tsx
  src/Checkbox/__tests__/Checkbox.test.tsx
  src/Checkbox/index.ts
  src/Checkbox/stories/Checkbox.stories.mdx
  src/Checkbox/styles/checkbox.scss
  src/index.ts
  yarn.lock
Labels: documentation, enhancement

#216 feat: Switch component
  package.json
  src/Switch/Switch.tsx
  src/Switch/__tests__/Switch.test.tsx
  src/Switch/index.ts
  src/Switch/stories/Switch.stories.mdx
  src/Switch/styles/switch.scss
  yarn.lock
Labels: documentation, enhancement

#240 feat: Creates a Link component
  .storybook/preview.js
  src/Button/stories/Button.stories.mdx
  src/Link/Link.tsx
  src/Link/__tests__/Link.test.tsx
  src/Link/index.ts
  src/Link/stories/Link.stories.mdx
  src/Link/styles/link.scss
  src/index.ts
Labels: documentation, enhancement

#251 feat: Creates textarea component
  package.json
  src/TextArea/TextArea.tsx
  src/TextArea/__tests__/TextArea.test.tsx
  src/TextArea/index.ts
  src/TextArea/stories/TextArea.stories.mdx
  src/TextArea/styles/textarea.scss
  src/index.ts
  yarn.lock
Labels: documentation, enhancement

#252 feat: Typography inverse
  src/Typography/Typography.tsx
  src/Typography/__tests__/Typography.test.tsx
  src/Typography/styles/typography.scss
Labels: documentation, enhancement

#253 typography caption and lead
  src/Typography/Typography.tsx
  src/Typography/stories/Typography.stories.mdx
  src/Typography/styles/typography.scss
Labels: enhancement

#310 feat: Adds FormControl component
  package.json
  src/FormControl/FormControl.tsx
  src/FormControl/__tests__/FormControl.test.tsx
  src/FormControl/index.ts
  src/FormControl/stories/FormControl.stories.mdx
  src/FormControl/styles/form-control.scss
  src/Input/Input.tsx
  src/Input/__tests__/Input.test.tsx
  src/Input/stories/Input.stories.mdx
  src/Input/styles/input.scss
  src/TextArea/TextArea.tsx
  src/TextArea/__tests__/TextArea.test.tsx
  src/TextArea/stories/TextArea.stories.mdx
  src/TextArea/styles/textarea.scss
  yarn.lock
Labels: enhancement
