Repository ocean-ds/ocean-web, pull requests merged in 2020-11, with the labels that each got.

#412 docs: include contributing guidelines
  .github/RELEASING.md
  CONTRIBUTING.md
Labels: documentation, help wanted

#433 docs(readme): adjust ocean-ds.min.css path
  README.md
Labels: documentation

#446 ci: add job to check and publish packages
  .circleci/config.yml
  .gitignore
  lerna.json
  package.json
  scripts/release.js
  yarn.lock
Labels: help wanted

#454 docs: include releasing guidelines
  .github/RELEASING.md
Labels: documentation, help wanted
