Repository ocean-ds/ocean-web, pull requests merged in 2020-06, with the labels that each got.

#9 feat: using mdx syntax to create stories
  .storybook/main.js
  .storybook/preview.js
  .vscode/extensions.json
  package.json
  src/Typography/Typography.tsx
  src/Typography/__tests__/Typography.test.tsx
  src/Typography/stories/Typography.stories.mdx
  src/Typography/stories/Typography.stories.tsx
  src/Typography/styles/typography.scss
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement

#12 docs: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/prlint.json
Labels: documentation

#10 ci: Circleci project setup
  .circleci/config.yml
  .gitignore
  package.json
  src/Typography/stories/Typography.stories.mdx
  src/index.ts
  yarn.lock
Labels: enhancement, help wanted
