Repository ocean-ds/ocean-web, pull requests merged in 2021-08, with the labels that each got.

#761 feat(link): include size property
  packages/ocean-core/src/components/_link.scss
  packages/ocean-react/src/Link/Link.tsx
  packages/ocean-react/src/Link/__tests__/Link.test.tsx
  packages/ocean-react/src/Link/stories/Link.stories.mdx
Labels: enhancement

#762 feat: update border-width for input, select and textarea
  packages/ocean-core/src/forms/_input.scss
  packages/ocean-core/src/forms/_select.scss
  packages/ocean-core/src/forms/_textarea.scss
  packages/ocean-react/src/Input/Input.tsx
  packages/ocean-react/src/Input/__tests__/Input.test.tsx
  packages/ocean-react/src/Input/examples/InputControlled.tsx
  packages/ocean-react/src/Input/stories/Input.stories.mdx
  packages/ocean-react/src/Select/Select.tsx
  packages/ocean-react/src/Select/__tests__/Select.test.tsx
  packages/ocean-react/src/Select/examples/SelectControlled.tsx
  packages/ocean-react/src/Select/stories/Select.stories.mdx
  packages/ocean-react/src/TextArea/TextArea.tsx
  packages/ocean-react/src/TextArea/__tests__/TextArea.test.tsx
  packages/ocean-react/src/TextArea/examples/TextAreaControlled.tsx
  packages/ocean-react/src/TextArea/stories/TextArea.stories.mdx
  packages/ocean-react/src/_util/useInputFilled.ts
Labels: enhancement, help wanted

#767 feat(button): add text-critical variant
  packages/ocean-core/src/components/_button.scss
  packages/ocean-react/src/Button/Button.tsx
  packages/ocean-react/src/Button/__tests__/Button.test.tsx
  packages/ocean-react/src/Button/stories/Button.stories.mdx
Labels: enhancement

#766 feat(checkbox): update border-width
  packages/ocean-core/src/forms/_checkbox.scss
Labels: enhancement

#765 feat(label): change font-weight from bold to regular
  packages/ocean-core/src/forms/_form-label.scss
Labels: enhancement

#764 docs(storybook): center story on canvas
  .storybook/preview.ts
  packages/ocean-react/src/Grid/stories/Col.stories.mdx
  packages/ocean-react/src/Grid/stories/Container.stories.mdx
  packages/ocean-react/src/Grid/stories/Grid.stories.mdx
  packages/ocean-react/src/Grid/stories/Row.stories.mdx
  packages/ocean-react/src/Select/stories/Select.stories.mdx
  packages/ocean-react/src/_stories/Examples.stories.mdx
Labels: documentation

#770 feat: add divider component
  packages/ocean-core/src/components/_all.scss
  packages/ocean-core/src/components/_divider.scss
  packages/ocean-react/src/Divider/Divider.tsx
  packages/ocean-react/src/Divider/__tests__/Divider.test.tsx
  packages/ocean-react/src/Divider/index.ts
  packages/ocean-react/src/Divider/stories/Divider.stories.mdx
  packages/ocean-react/src/index.ts
Labels: enhancement

#677 feat: add icon button component
  packages/ocean-core/src/components/_all.scss
  packages/ocean-core/src/components/_icon-button.scss
  packages/ocean-react/src/IconButton/IconButton.tsx
  packages/ocean-react/src/IconButton/__tests__/IconButton.test.tsx
  packages/ocean-react/src/IconButton/index.ts
  packages/ocean-react/src/IconButton/stories/IconButton.stories.mdx
  packages/ocean-react/src/index.ts
Labels: enhancement, help wanted

#774 feat(switch): add hover state, update border and non-checked styles
  packages/ocean-core/src/forms/_switch.scss
Labels: enhancement

#775 feat(checkbox): add Indeterminate state and fix colors
  packages/ocean-core/src/forms/_checkbox.scss
  packages/ocean-react/src/Checkbox/Checkbox.tsx
  packages/ocean-react/src/Checkbox/__tests__/Checkbox.test.tsx
  packages/ocean-react/src/Checkbox/stories/Checkbox.stories.mdx
Labels: enhancement

#768 feat: add alert component
  packages/ocean-core/src/components/_alert.scss
  packages/ocean-core/src/components/_all.scss
  packages/ocean-react/src/Alert/Alert.tsx
  packages/ocean-react/src/Alert/AlertIcon.tsx
  packages/ocean-react/src/Alert/__tests__/Alert.test.tsx
  packages/ocean-react/src/Alert/index.ts
  packages/ocean-react/src/Alert/stories/Alert.stories.mdx
  packages/ocean-react/src/index.ts
Labels: enhancement, help wanted

#786 fix(alert): adds a wrapper for content
  packages/ocean-react/src/Alert/Alert.tsx
  packages/ocean-react/src/Alert/AlertIcon.tsx
  packages/ocean-react/src/Alert/__tests__/Alert.test.tsx
  packages/ocean-react/src/Alert/stories/Alert.stories.mdx
Labels: bug

#785 docs(readme): include discord info
  README.md
Labels: documentation

#791 feat(input): add input adornment
  packages/ocean-core/src/forms/_input.scss
  packages/ocean-react/src/Input/Input.tsx
  packages/ocean-react/src/Input/__tests__/Input.test.tsx
  packages/ocean-react/src/Input/stories/Input.stories.mdx
Labels: enhancement

#798 feat(tag): add tag component
  packages/ocean-core/src/components/_all.scss
  packages/ocean-core/src/components/_tag.scss
  packages/ocean-react/src/Tag/Tag.tsx
  packages/ocean-react/src/Tag/TagIcon.tsx
  packages/ocean-react/src/Tag/__tests__/Tag.test.tsx
  packages/ocean-react/src/Tag/index.ts
  packages/ocean-react/src/Tag/stories/Tag.stories.mdx
Labels: enhancement
