Repository ocean-ds/ocean-web, pull requests merged in 2021-11, with the labels that each got.

#841 feat: create new component search
  packages/ocean-core/src/components/_all.scss
  packages/ocean-core/src/components/_search.scss
  packages/ocean-react/src/Search/Search.tsx
  packages/ocean-react/src/Search/__tests__/Search.test.tsx
  packages/ocean-react/src/Search/index.ts
  packages/ocean-react/src/Search/stories/Search.stories.mdx
  packages/ocean-react/src/index.ts
Labels: component

#839 chore: adding currency input component
  packages/ocean-core/src/forms/_input.scss
  packages/ocean-react/src/Input/Input.tsx
  packages/ocean-react/src/Input/__tests__/Input.test.tsx
  packages/ocean-react/src/Input/stories/Input.stories.mdx
Labels: enhancement

#840 fix: double select z-index problem
  packages/ocean-core/src/forms/_select.scss
Labels: bug
