Repository ocean-ds/ocean-web, pull requests merged in 2022-10, with the labels that each got.

#1013 feat: components adjustments
  packages/ocean-core/src/components/_badge.scss
  packages/ocean-core/src/components/_link.scss
  packages/ocean-core/src/components/_typography.scss
  packages/ocean-core/src/forms/_form-control.scss
  packages/ocean-react/src/Divider/__tests__/Divider.test.tsx
  packages/ocean-react/src/FileUploader/__tests__/FileUpload.test.tsx
  packages/ocean-react/src/FormControl/FormControl.tsx
  packages/ocean-react/src/FormControl/__tests__/FormControl.test.tsx
  packages/ocean-react/src/FormControl/stories/FormControl.stories.mdx
  packages/ocean-react/src/Input/Input.tsx
  packages/ocean-react/src/Input/__tests__/Input.test.tsx
  packages/ocean-react/src/Input/stories/0-Introduction.stories.mdx
  packages/ocean-react/src/Input/stories/WithLabelIconTooltip.stories.mdx
  packages/ocean-react/src/Link/Link.tsx
  packages/ocean-react/src/Link/LinkIcons.tsx
  packages/ocean-react/src/Link/__tests__/Link.test.tsx
  packages/ocean-react/src/Link/__tests__/LinkIcons.test.tsx
  packages/ocean-react/src/Link/stories/Link.stories.mdx
  packages/ocean-react/src/Search/__tests__/Search.test.tsx
  packages/ocean-react/src/Select/__tests__/Select.test.tsx
  packages/ocean-react/src/Stepper/__tests__/Stepper.test.tsx
  packages/ocean-react/src/TextArea/__tests__/TextArea.test.tsx
  packages/ocean-react/src/Typography/Typography.tsx
  packages/ocean-react/src/Typography/stories/Typography.stories.mdx
Labels: enhancement

#1021 fix: link component error
  packages/ocean-core/src/components/_link.scss
  packages/ocean-react/src/Link/Link.tsx
  packages/ocean-react/src/Link/stories/Link.stories.mdx
Labels: bug, documentation

#1007 feat: datepicker
  packages/ocean-core/src/components/_all.scss
  packages/ocean-core/src/components/_date-picker.scss
  packages/ocean-react/package.json
  packages/ocean-react/src/DatePicker/DatePicker.tsx
  packages/ocean-react/src/DatePicker/__tests__/DatePicker.test.tsx
  packages/ocean-react/src/DatePicker/index.ts
  packages/ocean-react/src/DatePicker/stories/0-Introducion.stories.mdx
  packages/ocean-react/src/DatePicker/stories/1-Props.stories.mdx
  packages/ocean-react/src/DatePicker/stories/2 - Playground.stories.mdx
  packages/ocean-react/src/_util/useDatePicker.ts
  packages/ocean-react/src/index.ts
  yarn.lock
Labels: enhancement, component

#1023 fix: datepicker
  packages/ocean-core/src/components/_date-picker.scss
  packages/ocean-react/src/DatePicker/DatePicker.tsx
  packages/ocean-react/src/DatePicker/__tests__/DatePicker.test.tsx
Labels: bug

#1027 fix: datepicker (remove input patterns)
  packages/ocean-react/src/DatePicker/DatePicker.tsx
  packages/ocean-react/src/DatePicker/__tests__/DatePicker.test.tsx
Labels: bug

#1030 feat: dateclass
  packages/ocean-core/src/components/_date-picker.scss
  packages/ocean-react/src/Date/DateHeader.tsx
  packages/ocean-react/src/Date/DatePicker.tsx
  packages/ocean-react/src/Date/DateRange.tsx
  packages/ocean-react/src/Date/__tests__/DatePicker.test.tsx
  packages/ocean-react/src/Date/__tests__/DateRange.test.tsx
  packages/ocean-react/src/Date/hooks/useDatePicker.ts
  packages/ocean-react/src/Date/hooks/useDateRange.ts
  packages/ocean-react/src/Date/index.ts
  packages/ocean-react/src/Date/stories/0 - Introducion.stories.mdx
  packages/ocean-react/src/Date/stories/DatePicker.stories.mdx
  packages/ocean-react/src/Date/stories/DateRange.stories.mdx
  packages/ocean-react/src/Date/types/DatePicker.types.ts
  packages/ocean-react/src/Date/types/DateRange.types.ts
  packages/ocean-react/src/Date/utils/dateUtils.ts
  packages/ocean-react/src/DatePicker/index.ts
  packages/ocean-react/src/DatePicker/stories/0-Introducion.stories.mdx
  packages/ocean-react/src/DatePicker/stories/1-Props.stories.mdx
  packages/ocean-react/src/DatePicker/stories/2 - Playground.stories.mdx
  packages/ocean-react/src/index.ts
Labels: component

#1032 fix: component link with icons
  packages/ocean-core/src/components/_link.scss
Labels: bug
